### ISSUE TITLE
Plot self-connecting edges

### ISSUE THREAD

**Issue by oliver-xie** [paulcbogdan/NiChord#4]
Hi - I am trying to use your package to plot connectome matrix and it worked great. I also wanted to plot a chord diagram of network connectivity with one node per network. It didn't plot the within-network (self-connecting) edges. I wonder if there is a way to visualize it.
Thanks,
Oliver

**Comment by paulcbogdan** [comment]
Hi Oliver,

This is an interesting suggestion, and it sounds like a reasonable feature. I'm picturing something like a circle on the chord diagram where a node's arc loops back in on itself. However, I don't have the time right now to work on something like this right now. If you want to implement it yourself, I'd be happy to take a look and accept a PR.

Also, for what it's worth, if you only have like 7 or so different networks, you may be better off reporting a correlation matrix triangle rather than a chord diagram. Those can be more precise and you can cleanly report the actual connectivity values. For instance, see Figure 3D and 3E here: https://royalsocietypublishing.org/doi/epdf/10.1098/rstb.2017.0284

Best,
Paul

**Comment by oliver-xie** [comment]
Thanks, that makes sense. I just thought this may be a good feature to have but showing the correlation matrix is also straightforward.
